---
- hosts: ansible
  become: true

  tasks:
  - name: create docker image using war file
    command: docker image build -t demo-image:v1.$BUILD_ID .
    args:
      chdir: /opt/docker

  - name: create tag to image
    command: docker image tag demo-image:v1.$BUILD_ID k2r2t2/demo-image:v1.$BUILD_ID

  - name: create tag latest to image
    command: docker image tag demo-image:v1.$BUILD_ID k2r2t2/demo-image:latest
    
  - name: push image on to dockerhub
    command: docker image push k2r2t2/demo-image:v1.$BUILD_ID

  - name: push image with latest tag on to dockerhub
    command: docker image push k2r2t2/demo-image:latest
    
  - name: remove old image on dockerhub
    command: docker image rmi demo-image:v1.$BUILD_ID k2r2t2/demo-image:v1.$BUILD_ID k2r2t2/demo-image:latest
    
  - name: remove docker images form ansible server
    command: docker rmi demo-image:latest k2r2t2/demo-image
    ignore_errors: yes
