apiVersion: apps/v1
kind: Deployment
metadata:
  name: demosharedlib-deployment
spec:
  selector:
    matchLabels:
      app: demosharedlib
  replicas: 2
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: demosharedlib
    spec:
      containers:
      - name: demosharedlib
        image: k2r2t2/demosharedlib
        imagePullPolicy: Always
        ports:
        - containerPort: 8080


---


apiVersion: v1
kind: Service
metadata:
  name: demosharedlib-service
  labels:
    app: demosharedlib
spec:
  selector:
    app: demosharedlib
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
